version: '3.8'

services:
  database:
    # container_name - optional
    # container_name: project3-database
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_TCP_PORT=3306
      - MYSQL_DATABASE=project3
    ports:
      - 3306:3306
    build: ./database 
    volumes:
      - project3-database:/var/lib/mysql
  backend:
    depends_on:
      - database
    # container_name: project3-backend
    ports:
      - 8080:8080
    environment:
      - NODE_ENV=compose
    build: ./backend
  frontend:
    depends_on:
      - backend
    # container_name: project3-frontend
    ports:
      - 3000:80
    build: ./frontend


volumes:
  project3-database: